## models, test, predict

In [3]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
model = LinearRegression()

In [ ]:
X = np.array([[1], [2], [3], [4], [5]])
y = np.array([30, 40, 50, 60, 70])


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)
# print(X_test)
# print(y_test)
model.fit(X_train, y_train)
predictVal = model.predict(X_test)

predictVal = np.clip(predictVal, 0, 100)
# setting range of prediction value of 0-100 => cause maximum marks is 100 and minimum marks is 0

In [19]:
print(predictVal)
print()
print(y_test)

[100.]

[40 70]


In [15]:
print(model.predict([[18]]))

[200.]


### Transformers, transform(), and fit_transform()

#### StandardScaler --> Transformer

In [ ]:
from sklearn.preprocessing import StandardScaler
# get tool or transformer


In [21]:
X = np.array([
    [500000],
    [900000],
    [300000]
])

scaler = StandardScaler() #call tool or transformer
val = scaler.fit_transform(X) #study & transform(scaling) the data

In [22]:
print(val)

[[-0.26726124]
 [ 1.33630621]
 [-1.06904497]]


#### OneHotEncoder --> Transformer

In [23]:
from sklearn.preprocessing import OneHotEncoder

In [24]:
X = np.array([
    ["Kolkata"],
    ["Delhi"],
    ["Mumbai"]
])

scaler = OneHotEncoder()
res = scaler.fit_transform(X)

In [27]:
print(res.toarray())

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
