## models, test, predict

In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [3]:
model = LinearRegression()

In [4]:
X = np.array([[1], [2], [3], [4], [5]])
y = np.array([30, 40, 50, 60, 70])


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)
# print(X_test)
# print(y_test)
model.fit(X_train, y_train)
predictVal = model.predict(X_test)

predictVal = np.clip(predictVal, 0, 100)
# setting range of prediction value of 0-100 => cause maximum marks is 100 and minimum marks is 0

In [5]:
print(predictVal)
print()
print(y_test)

[40. 70.]

[40 70]


#### Score checks the performance of the trained model on the test data.

0.0  → completely wrong\
0.5  → 50% correct\
0.8  → 80% correct\
1.0  → 100% correct

In [16]:
print(model.predict([[18]]))
print(model.score(X_test, y_test))

[200.]
1.0


#### `model.fit()` is not just memorizing it is also for continuous error correction and optimization

### Transformers, transform(), and fit_transform()

#### StandardScaler --> Transformer

In [7]:
from sklearn.preprocessing import StandardScaler
# get tool or transformer


In [8]:
X = np.array([
    [500000],
    [900000],
    [300000]
])

scaler = StandardScaler() #call tool or transformer
val = scaler.fit_transform(X) #study & transform(scaling) the data

In [9]:
print(val)

[[-0.26726124]
 [ 1.33630621]
 [-1.06904497]]


#### OneHotEncoder --> Transformer

In [10]:
from sklearn.preprocessing import OneHotEncoder

In [11]:
X = np.array([
    ["Kolkata"],
    ["Delhi"],
    ["Mumbai"]
])

scaler = OneHotEncoder()
res = scaler.fit_transform(X)

In [12]:
print(res.toarray()) # converting sparse matrix(res) into array(for learning purpose only)
#but in real cases we did not convert it into array and use that sparse matrix

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [13]:
print(res)

# (0, 1)    1.0

# means:
# row 0
# column 1
# value = 1

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3 stored elements and shape (3, 3)>
  Coords	Values
  (0, 1)	1.0
  (1, 0)	1.0
  (2, 2)	1.0


## SimpleImputer (Handling Missing Data)
#### SimpleImputer is a preprocessing tool in scikit-learn that: fills missing values using a chosen strategy.

In [14]:
from sklearn.impute import SimpleImputer

In [15]:
X = np.array([
    [20],
    [np.nan],
    [30]
])

imputer = SimpleImputer(strategy="mean")
filled = imputer.fit_transform(X)

print(filled)

[[20.]
 [25.]
 [30.]]
